from app import create_app, db
from app.models.tourism import TourismSpot

app = create_app()

spots = [
    {
        'name': 'Pantai Parangtritis',
        'description': 'Pantai ikonik Jogja dengan sunset romantis. Sempurna untuk momen valentine bersama pasangan. Nikmati deburan ombak dan angin sepoi-sepoi sambil berjalan di tepi pantai.',
        'location': 'Parangtritis, Kretek',
        'city': 'Bantul',
        'province': 'DI Yogyakarta',
        'latitude': -8.0254,
        'longitude': 110.3344,
        'category': 'pantai',
        'price_min': 10000,
        'price_max': 20000,
        'rating': 4.5,
        'total_reviews': 2341,
        'is_featured': True,
        'opening_hours': '24 Jam',
        'facilities': 'Parkir,Toilet,Warung Makan,Penyewaan ATV,Penyewaan Kuda'
    },
    {
        'name': 'Candi Borobudur',
        'description': 'Warisan dunia UNESCO yang megah. Saksikan matahari terbit bersama pasangan dari atas Borobudur untuk pengalaman valentine yang tak terlupakan.',
        'location': 'Borobudur',
        'city': 'Magelang',
        'province': 'Jawa Tengah',
        'latitude': -7.6079,
        'longitude': 110.2038,
        'category': 'budaya',
        'price_min': 50000,
        'price_max': 350000,
        'rating': 4.8,
        'total_reviews': 5621,
        'is_featured': True,
        'opening_hours': '06:00 - 17:00',
        'facilities': 'Parkir,Toilet,Museum,Pemandu Wisata,Restoran,Souvenir Shop'
    },
    {
        'name': 'Kebun Teh Kemuning',
        'description': 'Hamparan kebun teh hijau yang memukau di dataran tinggi. Udara sejuk dan pemandangan indah menjadikannya tempat romantis yang sempurna.',
        'location': 'Kemuning, Ngargoyoso',
        'city': 'Karanganyar',
        'province': 'Jawa Tengah',
        'latitude': -7.6215,
        'longitude': 111.1234,
        'category': 'alam',
        'price_min': 15000,
        'price_max': 25000,
        'rating': 4.6,
        'total_reviews': 1823,
        'is_featured': True,
        'opening_hours': '07:00 - 17:00',
        'facilities': 'Parkir,Toilet,Cafe,Spot Foto,Trekking'
    },
    {
        'name': 'Gunung Bromo',
        'description': 'Keajaiban alam Jawa Timur. Sunrise di Bromo adalah pengalaman romantis luar biasa yang akan dikenang seumur hidup bersama pasangan.',
        'location': 'Tengger, Probolinggo',
        'city': 'Probolinggo',
        'province': 'Jawa Timur',
        'latitude': -7.9425,
        'longitude': 112.9530,
        'category': 'alam',
        'price_min': 35000,
        'price_max': 320000,
        'rating': 4.9,
        'total_reviews': 8934,
        'is_featured': True,
        'opening_hours': '00:00 - 24:00',
        'facilities': 'Parkir,Toilet,Guide,Jeep Rental,Penginapan'
    },
    {
        'name': 'Kawah Ijen',
        'description': 'Blue fire yang memukau hanya ada dua di dunia! Fenomena api biru di Kawah Ijen adalah pengalaman magis yang romantic untuk pasangan pemberani.',
        'location': 'Licin, Banyuwangi',
        'city': 'Banyuwangi',
        'province': 'Jawa Timur',
        'latitude': -8.0580,
        'longitude': 114.2423,
        'category': 'alam',
        'price_min': 15000,
        'price_max': 100000,
        'rating': 4.7,
        'total_reviews': 3421,
        'is_featured': False,
        'opening_hours': '02:00 - 15:00',
        'facilities': 'Parkir,Toilet,Pemandu,Porter'
    },
    {
        'name': 'Taman Sari Yogyakarta',
        'description': 'Bekas taman kerajaan yang indah dengan arsitektur megah. Spot foto romantis yang instagramable dengan latar belakang bangunan bersejarah.',
        'location': 'Kraton',
        'city': 'Yogyakarta',
        'province': 'DI Yogyakarta',
        'latitude': -7.8104,
        'longitude': 110.3592,
        'category': 'budaya',
        'price_min': 15000,
        'price_max': 25000,
        'rating': 4.4,
        'total_reviews': 2156,
        'is_featured': False,
        'opening_hours': '08:00 - 14:00',
        'facilities': 'Parkir,Toilet,Pemandu,Souvenir'
    },
    {
        'name': 'Pantai Pink Lombok',
        'description': 'Pantai pasir pink yang langka dan eksotis di Lombok. Warna pink pantainya dari pecahan koral merah, sempurna untuk valentine yang unik!',
        'location': 'Sekaroh, Jerowaru',
        'city': 'Lombok Timur',
        'province': 'Nusa Tenggara Barat',
        'latitude': -8.8741,
        'longitude': 116.5041,
        'category': 'pantai',
        'price_min': 20000,
        'price_max': 50000,
        'rating': 4.6,
        'total_reviews': 1543,
        'is_featured': True,
        'opening_hours': '07:00 - 18:00',
        'facilities': 'Parkir,Toilet,Snorkeling,Pemandu'
    },
    {
        'name': 'Danau Toba',
        'description': 'Danau vulkanik terbesar di dunia. Keindahan danau dan pulau Samosir menjadikannya destinasi romantis yang memukau untuk pasangan.',
        'location': 'Parapat',
        'city': 'Simalungun',
        'province': 'Sumatera Utara',
        'latitude': 2.6845,
        'longitude': 98.8756,
        'category': 'danau',
        'price_min': 25000,
        'price_max': 150000,
        'rating': 4.7,
        'total_reviews': 4231,
        'is_featured': False,
        'opening_hours': '08:00 - 18:00',
        'facilities': 'Parkir,Toilet,Ferry,Penginapan,Restoran'
    },
    {
        'name': 'Labuan Bajo',
        'description': 'Surga tersembunyi di ujung barat Flores. Sunset di Labuan Bajo adalah salah satu yang terindah di dunia, sempurna untuk romantis bersama pasangan.',
        'location': 'Labuan Bajo',
        'city': 'Manggarai Barat',
        'province': 'Nusa Tenggara Timur',
        'latitude': -8.4539,
        'longitude': 119.8885,
        'category': 'bahari',
        'price_min': 50000,
        'price_max': 500000,
        'rating': 4.9,
        'total_reviews': 6123,
        'is_featured': True,
        'opening_hours': '07:00 - 18:00',
        'facilities': 'Diving,Snorkeling,Boat Tour,Penginapan,Restoran'
    },
    {
        'name': 'Bukit Teletubbies Bromo',
        'description': 'Padang savana hijau yang menyerupai latar Teletubbies. Tempat yang romantic dan unik untuk piknik bersama pasangan di alam terbuka.',
        'location': 'Ngadisari, Sukapura',
        'city': 'Probolinggo',
        'province': 'Jawa Timur',
        'latitude': -7.9234,
        'longitude': 112.9234,
        'category': 'alam',
        'price_min': 35000,
        'price_max': 100000,
        'rating': 4.6,
        'total_reviews': 2341,
        'is_featured': False,
        'opening_hours': '06:00 - 17:00',
        'facilities': 'Parkir,Toilet,Jeep,Pemandu'
    },
    {
        'name': 'Raja Ampat',
        'description': 'Surga bawah laut terbaik di dunia. Keindahan Raja Ampat yang tak tertandingi menjadikannya impian setiap pasangan untuk honeymoon.',
        'location': 'Waisai',
        'city': 'Raja Ampat',
        'province': 'Papua Barat',
        'latitude': -0.2339,
        'longitude': 130.5253,
        'category': 'bahari',
        'price_min': 100000,
        'price_max': 2000000,
        'rating': 5.0,
        'total_reviews': 9234,
        'is_featured': True,
        'opening_hours': '08:00 - 18:00',
        'facilities': 'Diving,Snorkeling,Homestay,Boat,Pemandu'
    },
    {
        'name': 'Bukit Bintang Yogyakarta',
        'description': 'Spot terbaik menikmati gemerlap lampu kota Jogja di malam hari. Romantis untuk dinner atau sekedar duduk berdua menikmati pemandangan.',
        'location': 'Patuk, Gunungkidul',
        'city': 'Gunungkidul',
        'province': 'DI Yogyakarta',
        'latitude': -7.8534,
        'longitude': 110.5123,
        'category': 'taman',
        'price_min': 5000,
        'price_max': 15000,
        'rating': 4.3,
        'total_reviews': 1234,
        'is_featured': False,
        'opening_hours': '17:00 - 23:00',
        'facilities': 'Parkir,Toilet,Warung Makan,Spot Foto'
    },
]

with app.app_context():
    TourismSpot.query.delete()
    db.session.commit()

    for s in spots:
        spot = TourismSpot(**s)
        db.session.add(spot)

    db.session.commit()
    print(f'✅ {len(spots)} destinasi wisata berhasil ditambahkan!')